const data = {
    products:[
        {
            _id:'1',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:12,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
        {
            _id:'2',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:10,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
        {
            _id:'3',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:20,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
        {
            _id:'4',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:120,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
        {
            _id:'5',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:120,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
        {
            _id:'6',
            name:'cup',
            category:'utensils',
            image:'/images/cup.jpg',
            price:120,
            rating:3.5,
            numReviews:10,
            description:'High qulaity products',
        },
    ],
};

export default data;